# Generated by Django 4.1.3 on 2022-12-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=50)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('PhoneNumber', models.IntegerField()),
                ('Address1', models.CharField(max_length=200)),
                ('Address2', models.CharField(blank=True, max_length=200)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip', models.IntegerField()),
                ('Country', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('InfoAboutUser', models.TextField(max_length=500)),
                ('AdventuresInfo', models.TextField(max_length=500)),
            ],
        ),
    ]
